# Generated by Django 5.1.7 on 2025-03-25 19:52

import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата отправки')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Заголовок главной страницы')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', verbose_name='Описание главной страницы')),
                ('image', models.ImageField(upload_to='homepage/', verbose_name='Background-изображение главной страницы')),
                ('title_about', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Заголовок первого раздела')),
                ('image_about', models.ImageField(upload_to='about/', verbose_name='Изображение')),
                ('description_about', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание первого раздела')),
                ('advantage1_title', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Заголовок преимущества 1')),
                ('advantage1_description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание преимущества 1')),
                ('advantage2_title', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Заголовок преимущества 2')),
                ('advantage2_description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание преимущества 2')),
                ('advantage3_title', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Заголовок преимущества 3')),
                ('advantage3_description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание преимущества 3')),
                ('title_service', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Заголовок второго раздела')),
                ('description_service', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание второго раздела')),
                ('title_work', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Заголовок третьего раздела')),
                ('description_work', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание третьего раздела')),
                ('contact_title', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Заголовок формы обратной связи')),
                ('contact_text', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Текст формы обратной связи')),
                ('footer_titleCompany', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Название компании')),
                ('footer_descriptionCompany', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание компании')),
                ('footer_titleNumber', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Заголовок телефона')),
                ('footer_phone', models.CharField(default='+7 (915) 777-73-14', max_length=20, verbose_name='Телефон')),
                ('footer_titleEmail', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Заголовок email')),
                ('footer_email', models.EmailField(default='reklamgrad@mail.ru', max_length=254, verbose_name='Email')),
                ('footer_titleMenu', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Заголовок меню навигации')),
                ('footer_titleMenu2', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Заголовок меню услуг')),
                ('footer_titleMenu3', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Заголовок меню работ')),
                ('footer_vk_url', models.URLField(default='https://vk.com/reklamgrad', verbose_name='Ссылка VK')),
                ('footer_copyright', django_ckeditor_5.fields.CKEditor5Field(default='&copy; 2025&nbsp; <a class="footer_btn" href="http://127.0.0.1:8000/#">REKLAMGRAD</a>', verbose_name='Текст копирайта')),
            ],
        ),
        migrations.CreateModel(
            name='PageService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Заголовок раздела')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание раздела')),
                ('contact_title', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Заголовок формы обратной связи')),
                ('right_titleMenu', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Название раздела справа')),
            ],
        ),
        migrations.CreateModel(
            name='PageWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Заголовок раздела')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание раздела')),
                ('more_work', django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='Заголовок новых работ')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', django_ckeditor_5.fields.CKEditor5Field(max_length=200, verbose_name='Название услуги')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', verbose_name='Описание')),
                ('image', models.ImageField(upload_to='services/', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title2', django_ckeditor_5.fields.CKEditor5Field(max_length=200, verbose_name='Название работы')),
                ('tip', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Тип работы')),
                ('description2', django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', verbose_name='Описание')),
                ('image2', models.ImageField(upload_to='works/', verbose_name='Изображение')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название пункта меню')),
                ('url', models.CharField(max_length=200, verbose_name='URL или якорь')),
                ('main_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='main.mainpage')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
            },
        ),
    ]
