# Generated by Django 5.1.7 on 2025-03-14 10:14

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='')),
                ('image', models.ImageField(upload_to='collections/', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title2', models.CharField(max_length=200, verbose_name='')),
                ('description2', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='')),
                ('image2', models.ImageField(upload_to='works/', verbose_name='')),
            ],
        ),
    ]
