# Generated by Django 5.1.7 on 2025-04-01 13:05

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpage',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='meta_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Мета-описание'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='meta_title',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, max_length=250, verbose_name='Мета-заголовок'),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='title',
            field=django_ckeditor_5.fields.CKEditor5Field(max_length=200, verbose_name='Заголовок'),
        ),
    ]
