# Generated by Django 5.1.7 on 2025-03-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='base_characteristics',
            field=models.TextField(blank=True, null=True, verbose_name='Основные характеристики'),
        ),
        migrations.AddField(
            model_name='collection',
            name='metall',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Металл'),
        ),
        migrations.AddField(
            model_name='collection',
            name='vstavka',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Вставка'),
        ),
    ]
