# Generated by Django 5.1.7 on 2025-03-25 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpage',
            name='footer_copyright',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='footer_descriptionCompany',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='footer_email',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='footer_phone',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='footer_titleCompany',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='footer_titleEmail',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='footer_titleMenu',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='footer_titleMenu2',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='footer_titleMenu3',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='footer_titleNumber',
        ),
        migrations.RemoveField(
            model_name='mainpage',
            name='footer_vk_url',
        ),
    ]
