# Generated by Django 5.1.7 on 2025-03-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='work',
            name='description2',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
    ]
