# Generated by Django 5.1.7 on 2025-04-01 13:23

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_staticpage_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpage',
            name='title',
            field=django_ckeditor_5.fields.CKEditor5Field(max_length=250, verbose_name='Заголовок'),
        ),
    ]
