# Generated by Django 5.1.7 on 2025-03-26 11:26

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_pageservice_delete_pagework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='description_about',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание раздела '),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='title_about',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Заголовок первого О нас'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='title_service',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Заголовок раздела Сервисы'),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='title_work',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Заголовок раздела Работы'),
        ),
    ]
