# Generated by Django 5.1.7 on 2025-03-13 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
