# Generated by Django 5.1.7 on 2025-03-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_mainpage_footer_copyright_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='company_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='company_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='copyright_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='vk_url',
            field=models.URLField(blank=True),
        ),
    ]
