# Generated by Django 5.1.7 on 2025-03-26 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_mainpage_description_about_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Данные об разделе Услуги', 'verbose_name_plural': 'Данные об разделе Услуги'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name': 'Данные об разделе Работы', 'verbose_name_plural': 'Данные об разделе Работы'},
        ),
    ]
