# Generated by Django 5.1.7 on 2025-03-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='description2',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
    ]
