# Generated by Django 5.1.7 on 2025-03-25 14:50

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_mainpage_company_description_mainpage_company_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='footer_copyright',
            field=django_ckeditor_5.fields.CKEditor5Field(default='&copy; 2025&nbsp; <a class="footer_btn" href="http://127.0.0.1:8000/#">REKLAMGRAD</a>', verbose_name='Текст копирайта'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='footer_descriptionCompany',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание компании'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='footer_email',
            field=models.EmailField(default='reklamgrad@mail.ru', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='footer_phone',
            field=models.CharField(default='+7 (915) 777-73-14', max_length=20, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='footer_titleCompany',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Название компании'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='footer_titleEmail',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Заголовок email'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='footer_titleMenu',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Заголовок меню навигации'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='footer_titleMenu2',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Заголовок меню услуг'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='footer_titleMenu3',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Заголовок меню работ'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='footer_titleNumber',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Заголовок телефона'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='footer_vk_url',
            field=models.URLField(default='https://vk.com/reklamgrad', verbose_name='Ссылка VK'),
        ),
    ]
