# Generated by Django 5.1.7 on 2025-04-01 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_staticpage_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staticpage',
            options={'verbose_name': 'Создание статических страниц', 'verbose_name_plural': 'Создать статические страниц'},
        ),
    ]
