# Generated by Django 5.1.7 on 2025-04-01 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_staticpage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staticpage',
            options={'verbose_name': 'Статическая страница', 'verbose_name_plural': 'Статические страницы'},
        ),
    ]
