# Generated by Django 5.1.7 on 2025-03-12 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_project_delete_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='date',
        ),
    ]
