# Generated by Django 5.1.7 on 2025-03-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_mainpage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'Пункт навигационного меню', 'verbose_name_plural': 'Пункты навигационного меню'},
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название пункта навигационно меню'),
        ),
    ]
