# Generated by Django 5.1.7 on 2025-03-26 11:53

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_menuitem_options_alter_menuitem_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='title_about',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Заголовок раздела О нас'),
        ),
    ]
