# Generated by Django 5.1.7 on 2025-03-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_collection_description_alter_collection_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.CharField(max_length=100),
        ),
    ]
