# Generated by Django 5.1.7 on 2025-03-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_review_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title2', models.CharField(max_length=200, verbose_name='Название')),
                ('description2', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image2', models.ImageField(upload_to='works/', verbose_name='Изображение')),
            ],
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='base_characteristics',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='metall',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='vstavka',
        ),
    ]
