# Generated by Django 5.1.7 on 2025-03-13 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_work_delete_review_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='description2',
        ),
    ]
